KBV 371 add validation to manual address fields
alphagov/di-ipv-cri-address-front pull request #113
Opened 2022-05-09 16:24 UTC by MattBidewell

## Proposed changes

### What changed

Add validation rules to the manual address page.

In this PR, it is mostly validation rules being added alongside tests. I also took the opportunity to do a tiny refactor of a variable name that was using snake case rather than camelCase... I suspect I may do more of that in the future.

### Why did it change

To reduce the number of mistakes when adding an address to the store, we've added a number of validation methods to stop the user when they're adding their details. 

### Issue tracking

- [KBV-371](https://govukverify.atlassian.net/browse/KBV-371)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

### Other considerations

2022-05-09 16:26 UTC, MattBidewell commented on src/app/address/controllers/addressSearch.js
> -    const addressPostcode = req.body["address-search"];
refactored this variable name..

2022-05-09 16:53 UTC, jkunle commented on src/app/address/validators/addressValidator.js
> +    if (date.getFullYear() > new Date().getFullYear()) {
Wonder if you could use the evaluation `date.getFullYear() > new Date().getFullYear()` as the return value, since it is boolean

2022-05-09 16:54 UTC, jkunle commented on src/app/address/validators/addressValidator.js
> +    if (!houseName.trim() && !houseNumber.trim()) {
same as above, unless am missing something pecular stuff that means you need to do it this way

2022-05-09 16:56 UTC, jkunle commented on src/app/address/validators/addressValidator.js
> +    return val?.length <= 60;
Maybe, you could use const here const SIXTY = 60

2022-05-09 18:21 UTC, merlinc requested changes
Looks good, but there was a lot of examples and documentation that I hadn't shown you, so I think there's a lot of code you don't need to write :)

2022-05-10 08:39 UTC, MattBidewell commented on src/locales/en/default.yml
> +  streetNameLength: Check you've entered your street name correctly
Nice! 

Classic over engineering when theres a simple solution, thank you! 
Resolved.

2022-05-10 15:58 UTC, merlinc approved these changes

2022-05-10 15:59 UTC, merged