Date Drift Refactoring
alphagov/di-ipv-cri-address-front pull request #678
Opened 2023-05-09 09:31 UTC by rahulGDS

## Proposed changes
 Date Drift issue fix

### What changed

Code to automatically decide the year to be entered

### Why did it change

### Issue tracking

- [OJ-XXXX](https://govukverify.atlassian.net/browse/OJ-XXXX)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2023-05-10 11:22 UTC, merlinc requested changes

2023-05-10 11:22 UTC, merlinc commented on test/browser/features/address-confirm.feature
> +      When they add their residency date "current"
Perhaps something along the lines of:
      `When they add their residency date with a recent move year`
and
      `When they add their residency date an older move year`
      
or maybe there's better language than that?

2023-05-12 10:00 UTC, rahulGDS commented on test/browser/features/address-confirm.feature
> +      When they add their residency date "current"
Done

2023-05-15 10:25 UTC, merlinc approved these changes
LGTM

2023-05-15 13:02 UTC, merged